### ISSUE TITLE
[Low priority] Add support for complex protobuf mesasges

### ISSUE THREAD

**Issue by vzadrija** [yaak-ai/rbyte#40]
## Background:
This issue arose when we wanted to read [locations]( https://github.com/yaak-ai/idl-repo/blob/f728cf287074867850a71cd182c7860c1ec59984/osm/proto/ways.proto
) for OSM features along with the `highway type` and the `surface`:

```
repeated LocationFix locations = 1;
```

The temporary solution was to override the `McapDataFrameBuilder` with a combo of explode/unnest/etc on the locations column to turn it into locations.latitude, locations.longitude.

## TODO:
Find a way to read `locations` message in `rbyte`

## Environment:
mcap: `/nas/drives/yaak/data/G1-00436/2024-04-22--15-59-18/osm.mcap`

`DATA_DIR = "/nas/drives/yaak/data"`

Config

```yaml
_target_: rbyte.Dataset
_recursive_: false
_convert_: all
inputs:
  G1-00436/2024-04-22--15-59-18:
    sources:
      cam_front_left:
        index_column: meta/ImageMetadata.cam_front_left/frame_idx
        source:
          _target_: rbyte.io.FfmpegFrameSource
          path: ${data_dir}/G1-00436/2024-04-22--15-59-18/cam_front_left.defish.mp4
          resize_shorter_side: 1080
    samples:
      pipeline:
        _target_: pipefunc.Pipeline
        validate_type_annotations: false
        cache_type: disk
        cache_kwargs:
          cache_dir: /tmp/rbyte-cache2
        functions:
        - _target_: pipefunc.PipeFunc
          func:
            _target_: rbyte.io.YaakMetadataDataFrameBuilder
            fields:
              rbyte.io.yaak.proto.sensor_pb2.ImageMetadata:
                time_stamp:
                  _target_: polars.Datetime
                  time_unit: ns
                frame_idx:
                  _target_: polars.Int32
                camera_name:
                  _target_: polars.Enum
                  categories:
                  - cam_front_center
                  - cam_front_left
                  - cam_front_right
                  - cam_left_forward
                  - cam_right_forward
                  - cam_left_backward
                  - cam_right_backward
                  - cam_rear
              rbyte.io.yaak.proto.can_pb2.VehicleMotion:
                time_stamp:
                  _target_: polars.Datetime
                  time_unit: ns
                speed:
                  _target_: polars.Float32
                gear:
                  _target_: polars.Enum
                  categories:
                  - "0"
                  - "1"
                  - "2"
                  - "3"
              rbyte.io.yaak.proto.sensor_pb2.Gnss:
                time_stamp:
                  _target_: polars.Datetime
                  time_unit: ns
                hp_loc_latitude:
                  _target_: polars.Float32
                hp_loc_longitude:
                  _target_: polars.Float32
                hp_loc_altitude:
                  _target_: polars.Float32
          output_name: output
          scope: metadata
          cache: true
        - _target_: pipefunc.PipeFunc
          func:
            _target_: hydra.utils.get_method
            path: utils.augment_metadata
          output_name: metadata_augmented
          renames:
            input: metadata.output
        - _target_: pipefunc.PipeFunc
          func:
            _target_: rbyte.io.McapDataFrameBuilder
            decoder_factories:
            - rbyte.utils._mcap.ProtobufDecoderFactory
            fields:
              osm/Way:
                start:
                  _target_: polars.Datetime
                  time_unit: ns
                end:
                  _target_: polars.Datetime
                  time_unit: ns
                lanes:
                  _target_: polars.UInt32
                highway:
                  _target_: polars.Enum
                  categories:
                  - motorway
                  - trunk
                  - primary
                  - secondary
                  - tertiary
                  - residential
                  - motorway_link
                  - trunk_link
                  - primary_link
                  - secondary_link
                  - tertiary_link
                  - living_street
                  - service
                  - unclassified
                  - raceway
                  - track
                surface:
                  _target_: polars.Enum
                  categories:
                  - paved
                  - asphalt
                  - concrete
                  - sett
                  - cobblest
                  - paving_s
                  - dirt
                  - grass
                  - ground
                  - unpaved
                  - unknown
          output_name: output
          bound:
            path: ${data_dir}/G1-00436/2024-04-22--15-59-18/osm.mcap
          scope: mcap
        - _target_: pipefunc.PipeFunc
          func:
            _target_: pipefunc.helpers.collect_kwargs
            parameters:
            - meta
            - mcap
          output_name: data
          renames:
            meta: metadata_augmented
            mcap: mcap.output
        - _target_: pipefunc.PipeFunc
          func:
            _target_: aligner.PartialDataFrameAligner
            separator: /
            fields:
              meta:
                ImageMetadata.cam_front_left:
                  key: time_stamp
                VehicleMotion:
                  key: time_stamp
                  columns:
                    speed:
                      method: interp
                    gear:
                      method: asof
                      tolerance: 100ms
                      strategy: nearest
                    distance:
                      method: interp
                Gnss:
                  key: time_stamp
                  columns:
                    hp_loc_latitude:
                      method: asof
                      tolerance: 100ms
                      strategy: nearest
                    hp_loc_longitude:
                      method: asof
                      tolerance: 100ms
                      strategy: nearest
                    hp_loc_altitude:
                      method: asof
                      tolerance: 100ms
                      strategy: nearest
              mcap:
                osm/Way:
                  key: start
                  columns:
                    start:
                      method: asof
                      tolerance: 500ms
                      strategy: nearest
                    end:
                      method: asof
                      tolerance: 500ms
                      strategy: nearest
                    lanes:
                      method: asof
                      tolerance: 500ms
                      strategy: nearest
                    highway:
                      method: asof
                      tolerance: 500ms
                      strategy: nearest
                    surface:
                      method: asof
                      tolerance: 500ms
                      strategy: nearest
          output_name: data_aligned
          renames:
            input: data
        - _target_: pipefunc.PipeFunc
          func:
            _target_: rbyte.io.DataFrameFilter
            predicate: "true"
          output_name: data_filtered
          renames:
            input: data_aligned
        - _target_: pipefunc.PipeFunc
          func:
            _target_: rbyte.io.VideoDataFrameBuilder
            fields:
              frame_idx:
                _target_: polars.Int32
          output_name: data_cam_front_left
          bound:
            path: ${data_dir}/G1-00436/2024-04-22--15-59-18/cam_front_left.defish.mp4
        - _target_: pipefunc.PipeFunc
          func:
            _target_: hydra.utils.get_method
            path: polars.DataFrame.join
          output_name: data_joined
          renames:
            self: data_filtered
            other: data_cam_front_left
          bound:
            how: semi
            left_on: meta/ImageMetadata.cam_front_left/frame_idx
            right_on: frame_idx
        - _target_: pipefunc.PipeFunc
          renames:
            input: data_joined
          output_name: samples
          func:
            _target_: rbyte.FixedWindowSampleBuilder
            index_column: meta/ImageMetadata.cam_front_left/frame_idx
            every: 1i
            period: 1i
            length: 1
      kwargs:
        metadata:
          path: ${data_dir}/G1-00436/2024-04-22--15-59-18/metadata.log

```
