### ISSUE TITLE
bug: per drive filter

### ISSUE THREAD

**Issue by sandhawalia** [yaak-ai/rbyte#52]
Fix applying global sample filtering, this got introduced in https://github.com/yaak-ai/rbyte/pull/36
This is needed for getting samples for each drive which are filtered by timestamps or a filter conditioned on the drive. f.ex 

This is also need for training on collections built with nutron and natural language search. 

```
dataset:
  _target_: rbyte.Dataset
  _recursive_: false
  _convert_: all
  inputs:
    #@ for episode_id, episode in episodes.items():
    (@=episode_id@):
      sources:
        #@ for source_id in cameras:
        (@=source_id@):
          index_column: "meta/ImageMetadata.(@=source_id@)/frame_idx"
          source:
            _target_: rbyte.io.FfmpegFrameSource
            path: "${data_dir}/(@=episode[0]@)/(@=source_id@).pii.mp4"
        #@ end

      samples:
        pipeline:
          _target_: pipefunc.Pipeline
          validate_type_annotations: false
          cache_type: disk
          cache_kwargs:
            cache_dir: ./rbyte-cache
          functions:
            - _target_: pipefunc.PipeFunc
              scope: yaak_metadata
              output_name: output
              cache: true
              func:
                _target_: hydra.utils.get_method
                path: rbyte.io.build_yaak_metadata_dataframe

            - _target_: pipefunc.PipeFunc
              func:
                _target_: pipefunc.helpers.collect_kwargs
                parameters: [meta]
              renames:
                meta: yaak_metadata.output
              output_name: data

            - _target_: pipefunc.PipeFunc
              renames:
                input: data
              output_name: data_aligned
              func:
                _target_: rbyte.io.DataFrameAligner
                separator: /
                fields:
                  meta:
                    ImageMetadata.(@=cameras[0]@):
                      key: time_stamp

                    #@ for camera in cameras[1:]:
                    ImageMetadata.(@=camera@):
                      key: time_stamp
                      columns:
                        frame_idx:
                          method: asof
                          tolerance: 20ms
                          strategy: nearest
                        time_stamp:
                          method: asof
                          tolerance: 50ms
                          strategy: nearest
                    #@ end

                    VehicleMotion:
                      key: time_stamp
                      columns:
                        speed:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        speed_dashboard:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        steering_angle:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        steering_angle_normalized:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        gas_pedal_normalized:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        brake_pedal_normalized:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        acceleration_x:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        acceleration_y:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        gear:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest

                    VehicleState:
                      key: time_stamp
                      columns:
                        turn_signal:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest

                    Gnss:
                      key: time_stamp
                      columns:
                        hp_loc_latitude:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        hp_loc_longitude:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        hp_loc_altitude:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        heading:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        heading_error:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        speed:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest
                        speed_error:
                          method: asof
                          tolerance: 100ms
                          strategy: nearest

            - _target_: pipefunc.PipeFunc
              renames:
                input: data_aligned
              output_name: data_smoothed
              func:
                _target_: utils.RollingMeanProcessor
                index_column: meta/Gnss/heading
                window_size: 15
                center: true

            - _target_: pipefunc.PipeFunc
              renames:
                input: data_smoothed
              output_name: data_elapsed
              func:
                _target_: utils.ElapsedTimeProcessor
                sources:
                  #@ for source_id in cameras:
                  (@=source_id@): "meta/ImageMetadata.(@=source_id@)/time_stamp"
                  #@ end

            - _target_: pipefunc.PipeFunc
              renames:
                input: data_elapsed
              output_name: data_filtered
              func:
                _target_: rbyte.io.DataFrameFilter
                predicate: |
                  (@=episode[2]@)

            - _target_: pipefunc.PipeFunc
              renames:
                input: data_filtered
              output_name: samples
              func:
                _target_: rbyte.FixedWindowSampleBuilder
                index_column: meta/ImageMetadata.(@=cameras[0]@)/frame_idx
                every: 3i
                period: 1i
```
